version: "latest"

services:
  szeyuan:
    build:
      context: ./
      platforms:
        - "linux/arm64"
      dockerfile: "Dockerfile"
    image: "szeyuan/humble/ela2.0"
    command: /bin/bash
    privileged: true
    # stdin_open: true
    stdin_open: true # docker run -i
    tty: true
    environment:
      DISPLAY: $DISPLAY
    network_mode: "host"
    user: "syt"
    volumes:
      - ./ros/ros_ws:/home/ros/ros_ws
      - ./syt/ros_ws:/home/syt/ros_ws
    #   - /dev/bus/usb/001/003:/dev/video0:uid=1000,gid=1000
    # devices:
    #   # - /dev/bus/usb/001/010:/dev/ttyUSB0
    #   - /dev/bus/usb/001/003:/dev/video0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]